create table users(
	id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
	fullname varchar(50),
	email varchar(50),
	photo varchar(500),
	password varchar(50),
	birthday date,
	gender boolean,
	profession varchar(50),
	married boolean,
	note varchar(1000)

)
select * from users
